add_newline = false
format = """\
[](fg:bright-yellow)\
$os\
[](fg:bright-yellow)\
[](fg:yellow)\
[](fg:yellow inverted)\
$username\
$hostname\
[](fg:yellow)\
[](fg:black inverted bold dimmed)\
$directory\
[](fg:black bold dimmed)\
($git_branch)\
($git_status)\
($fill )\
($python )\
($jobs )\
([](fg:red)$status[](fg:red inverted)[](fg:red))\
[](fg:yellow dimmed)\
$time\
[](fg:yellow dimmed)
($character) \
"""

right_format = """\
"""

[character]
format = '[$symbol](bold)'
success_symbol = '[»](green)'
error_symbol = '[»](red)'
vimcmd_symbol = '[-](green)'
vimcmd_replace_one_symbol = '[_](purple)'
vimcmd_replace_symbol = '[_](purple)'
vimcmd_visual_symbol = '[█](green)'

[directory]
style = 'fg:black bg:white inverted bold dimmed'
format = """\
[$path]($style)\
[$read_only]($read_only_style)\
"""
truncation_length = 4
truncation_symbol = '…/'
read_only = '󰌾'

[fill]
symbol = '>'
style = 'fg:yellow dimmed'

[jobs]
format = '[$symbol$number]($style)'
symbol = ''
style = 'fg:purple'

[hostname]
ssh_only = true
style = 'bg:yellow fg:black'
format = '[@$hostname]($style)'

[git_branch]
style = 'fg:bright-yellow'
symbol = '󰘬'
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
style = 'fg:yellow'
renamed = '~'
deleted = '-'
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[os]
style = 'bg:bright-yellow fg:black'
format = '[$symbol ($version)]($style)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ' '
Android = ''
Arch = '󰣇'
Debian = ''
Kali = ''
Linux = ''
Macos = ''
Mint = '󰣭'
Pop = ''
Raspbian = ''
Redhat = '󱄛'
RedHatEnterprise = '󱄛'
Ubuntu = ''
Unknown = '?'
Windows = ''

[python]
symbol = ''
format = '[$symbol$virtualenv(:$version)]($style)'
version_format = '$major.$minor'

[status]
format = '[$symbol $status]($style)'
symbol = '󰀪'
not_executable_symbol = '󱏏'
not_found_symbol = ''
style = 'bg:red fg:yellow'
disabled = false

[time]
format = '[ $time]($style)'
style = 'fg:yellow bg:black dimmed inverted'
disabled = false

[username]
style_root = 'bg:yellow fg:red underline'
style_user = 'bg:yellow fg:black'
format = '[ $user]($style)'
show_always = true
