# ====================
# BEHAVIOUR
# ====================

# Do not rename windows
set-option -g allow-rename off

# Images
set-option -g allow-passthrough on
set-option -ga update-environment TERM
set-option -ga update-environment TERM_PROGRAM

# Start at 1
set-option -g base-index 1
set-option -g pane-base-index 1

# ====================
# KEY BINDINGS
# ====================

# Leader: ctrl + e
set-option -g prefix C-e

# Send leader to nested sessions
bind-key e send-prefix

# Reload Tmux conf
unbind-key r
bind-key r source-file ~/.tmux.conf \; display 'Config reloaded!'

# Disable mouse
set-option -g mouse off

# Split panes with: | and -
unbind-key '%'
unbind-key '"'
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

# Vi-like movements between panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Vi-like pane resizing
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# ====================
# APPEARANCE
# ====================

# Status bar position
set-option -g status-position top
set-option -g status-justify centre

# Status bar left
set-option -g status-left '#[reverse]#[noreverse] #{host} #[bg=terminal fg=blue]#[bg=terminal fg=blue dim]#[bg=yellow reverse] 󰍹 #{session_name} #[bg=terminal,fg=blue,noreverse,dim]'
set-option -g status-left-length 30
set-option -g status-left-style 'bg=blue fg=black'

# Status bar center
set-option -g status-style 'bg=terminal fg=blue'
set-window-option -g window-status-format ' #[fg=blue dim][#I:#W]'
set-window-option -g window-status-current-format ' #[fg=blue bright underscore][#I:#W]'

# Status bar right
set-option -g status-right '#[bg=terminal fg=blue noreverse dim]#[default]  %H:%M#[noreverse]'
set-option -g status-right-length 30
set-option -g status-right-style 'bg=black fg=blue dim reverse'

# Pane border
set-option -g pane-active-border-style 'fg=bluenbold'
set-option -g pane-border-style 'fg=grey dim'
set-option -g pane-border-indicators both
set-option -g pane-border-lines double

# Message
set-option -g message-style 'bg=blue fg=black'

# Pane number and clock
set-option -g display-panes-active-colour blue
set-option -g display-panes-colour colour240
set-window-option -g clock-mode-color blue

# Window mode
set-option -g mode-style 'bg=blue fg=black'
